language: c

before_install:
    # update package list
    - sudo apt-get update -qq

install:
    # install implicit build dependencies
    - sudo apt-get install -qq --no-install-recommends build-essential fakeroot devscripts
    # install build dependencies
    - sudo mk-build-deps --install debian/control

script:
    # build the debian package
    - dpkg-buildpackage -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc
#notifications:
#  email: false
