sudo: required

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=jessie TRAVIS_DEBIAN_BACKPORTS=true

services:
  - docker

before_script:
  # fetch all tags (not done due travis cloning with depth=50)
  - git fetch --tags

script:
  # build the debian package
  - wget -O- http://travis.debian.net/script.sh | sh -

after_script:
  # run lintian after build
  - sudo add-apt-repository -y ppa:waja/trusty-backports
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends lintian
  - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc

#notifications:
#  email: false

branches:
  except:
    - /^debian\/\d/
