sudo: required

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=jessie TRAVIS_DEBIAN_BACKPORTS=true

services:
  - docker

script:
  # build the debian package
  - wget -O- http://travis.debian.net/script.sh | sh -

#notifications:
#  email: false

branches:
  except:
    - /^debian\/\d/
